import * as esbuild from "esbuild";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import fg from "fast-glob";
import type { ResolvedVextFrontendConfig } from "../contract/types.js";

export interface ExtractJscssOptions {
  rootDir: string;
  generatedDir: string;
  config: ResolvedVextFrontendConfig;
}

export interface ExtractJscssResult {
  files: string[];
  cssPath?: string;
  cssText: string;
}

export async function extractJscssStyles(
  options: ExtractJscssOptions,
): Promise<ExtractJscssResult> {
  if (!options.config.styles.jscss.enabled) {
    return { files: [], cssText: "" };
  }

  const files = await scanJscssFiles(options.config);
  if (files.length === 0) {
    return { files, cssText: "" };
  }

  await mkdir(options.generatedDir, { recursive: true });
  const entryPath = path.join(options.generatedDir, "jscss-extract-entry.ts");
  const bundlePath = path.join(options.generatedDir, "jscss-extract.mjs");
  const cssPath = path.join(options.generatedDir, "vext-jscss.css");

  await writeFile(
    entryPath,
    renderExtractorEntry(options.generatedDir, files),
    "utf-8",
  );

  await esbuild.build({
    entryPoints: [entryPath],
    outfile: bundlePath,
    bundle: true,
    platform: "node",
    format: "esm",
    target: "node20",
    logLevel: "silent",
    plugins: [createJscssResolverPlugin(options.config)],
  });

  const module = (await import(
    `${pathToFileURL(bundlePath).href}?v=${Date.now()}`
  )) as { default?: string };
  const cssText = module.default ?? "";
  await writeFile(cssPath, cssText ? `${cssText}\n` : "", "utf-8");

  return { files, cssPath, cssText };
}

async function scanJscssFiles(
  config: ResolvedVextFrontendConfig,
): Promise<string[]> {
  if (!existsSync(config.root)) return [];
  const files = await fg(config.styles.jscss.files, {
    cwd: config.root,
    absolute: true,
    onlyFiles: true,
    ignore: ["**/*.d.ts", "**/*.test.*", "**/*.spec.*"],
  });
  return files.sort((a, b) => a.localeCompare(b));
}

function renderExtractorEntry(generatedDir: string, files: string[]): string {
  const imports = files
    .map(
      (file, index) =>
        `import ${JSON.stringify(toImportSpecifier(generatedDir, file))}; // ${index}`,
    )
    .join("\n");
  return `/* This file is generated by vextjs. Do not edit it by hand. */
import { __vextGetStyleSheet } from "vextjs/style";
${imports}

export default __vextGetStyleSheet();
`;
}

function createJscssResolverPlugin(
  config: ResolvedVextFrontendConfig,
): esbuild.Plugin {
  return {
    name: "vext-jscss-resolver",
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        if (args.path === "vextjs/style") {
          return { path: resolveVextStyleModule() };
        }
        const aliasTarget = resolveAliasImport(config, args.path);
        if (aliasTarget) {
          return { path: resolveExistingModulePath(aliasTarget) };
        }
        return undefined;
      });
    },
  };
}

function resolveVextStyleModule(): string {
  const sourcePath = fileURLToPath(
    new URL("../style/index.ts", import.meta.url),
  );
  if (existsSync(sourcePath)) return sourcePath;
  return fileURLToPath(new URL("../style/index.js", import.meta.url));
}

function resolveAliasImport(
  config: ResolvedVextFrontendConfig,
  importPath: string,
): string | undefined {
  for (const [alias, target] of Object.entries(config.alias)) {
    if (importPath === alias) return target;
    if (importPath.startsWith(`${alias}/`)) {
      return path.join(target, importPath.slice(alias.length + 1));
    }
  }
  return undefined;
}

const JSCSS_RESOLVE_EXTENSIONS = [".ts", ".js", ".tsx", ".jsx", ".json"];

function resolveExistingModulePath(filePath: string): string {
  if (existsSync(filePath)) return filePath;
  for (const extension of JSCSS_RESOLVE_EXTENSIONS) {
    const candidate = `${filePath}${extension}`;
    if (existsSync(candidate)) return candidate;
  }
  for (const extension of JSCSS_RESOLVE_EXTENSIONS) {
    const candidate = path.join(filePath, `index${extension}`);
    if (existsSync(candidate)) return candidate;
  }
  return filePath;
}

function toImportSpecifier(fromDir: string, targetPath: string): string {
  const relative = path.relative(fromDir, targetPath).replace(/\\/g, "/");
  return relative.startsWith(".") ? relative : `./${relative}`;
}
