import * as esbuild from "esbuild";
import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import fg from "fast-glob";
import type { ResolvedVextFrontendConfig } from "../contract/types.js";
import { withProjectOwner } from "../../lib/project/owner.js";
import { ArtifactDraft } from "../../lib/project/artifact-draft.js";
import type { ArtifactCandidate } from "../../lib/project/artifact-transaction.js";
import { createArtifactDraftPlugin } from "../../lib/build/artifact-draft-plugin.js";
import { evaluateGeneratedEsmString } from "../../lib/build/generated-esm.js";

export interface ExtractJscssOptions {
  rootDir: string;
  generatedDir: string;
  config: ResolvedVextFrontendConfig;
  signal?: AbortSignal;
}

export interface ExtractJscssResult {
  files: string[];
  cssPath?: string;
  cssText: string;
}

export function createJscssBuildDefines(
  config: ResolvedVextFrontendConfig,
): Record<string, string> {
  const jscss = config.styles.jscss;
  return {
    __VEXT_JSCSS_RUNTIME_ADAPTER__: JSON.stringify(jscss.runtimeAdapter),
    __VEXT_JSCSS_DYNAMIC_VARS__: JSON.stringify(jscss.dynamicVars),
    __VEXT_JSCSS_RECIPES__: JSON.stringify(jscss.recipes),
  };
}

export async function extractJscssStyles(
  options: ExtractJscssOptions,
): Promise<ExtractJscssResult> {
  return withProjectOwner(
    options.rootDir,
    "build",
    [options.generatedDir],
    async () => {
      const planned = await createJscssArtifacts(options);
      for (const file of planned.artifacts) {
        await mkdir(path.dirname(file.path), { recursive: true });
        await writeFile(file.path, file.contents);
      }
      return planned.result;
    },
  );
}

export async function createJscssArtifacts(
  options: ExtractJscssOptions,
): Promise<{ result: ExtractJscssResult; artifacts: ArtifactCandidate[] }> {
  if (!options.config.styles.jscss.enabled) {
    return { result: { files: [], cssText: "" }, artifacts: [] };
  }

  const files = await scanJscssFiles(options.config);
  if (files.length === 0) {
    return { result: { files, cssText: "" }, artifacts: [] };
  }

  const entryPath = path.join(options.generatedDir, "jscss-extract-entry.ts");
  const bundlePath = path.join(options.generatedDir, "jscss-extract.mjs");
  const cssPath = path.join(options.generatedDir, "vext-jscss.css");

  const draft = new ArtifactDraft(options.rootDir, [
    { outDir: options.generatedDir, producer: "frontend-generated" },
  ]);
  const artifacts: ArtifactCandidate[] = [
    {
      path: entryPath,
      contents: renderExtractorEntry(options.generatedDir, files),
    },
  ];
  draft.add(artifacts[0]!);
  try {
    const built = await esbuild.build({
      entryPoints: [entryPath],
      outfile: bundlePath,
      bundle: true,
      platform: "node",
      format: "esm",
      target: "node20",
      logLevel: "silent",
      write: false,
      define: createJscssBuildDefines(options.config),
      // 保留同一个原生 meta 对象，解构/别名读取也必须看到最终逻辑位置。
      banner: {
        js: [
          `import.meta.url = ${JSON.stringify(pathToFileURL(bundlePath).href)};`,
          `import.meta.filename = ${JSON.stringify(bundlePath)};`,
          `import.meta.dirname = ${JSON.stringify(path.dirname(bundlePath))};`,
        ].join("\n"),
      },
      plugins: [
        createArtifactDraftPlugin(draft),
        createJscssResolverPlugin(options.config),
      ],
    });
    const bundle = built.outputFiles.find(
      (file) => path.relative(bundlePath, file.path) === "",
    );
    if (!bundle) throw new Error("[vextjs] JSCSS bundle was not generated.");
    const cssText = await withProjectOwner(
      options.rootDir,
      "build",
      [options.generatedDir],
      () =>
        evaluateGeneratedEsmString({
          rootDir: options.rootDir,
          logicalPath: bundlePath,
          contents: bundle.contents,
          signal: options.signal,
        }),
    );
    artifacts.push({ path: bundlePath, contents: bundle.contents });
    artifacts.push({ path: cssPath, contents: cssText ? `${cssText}\n` : "" });
    return { result: { files, cssPath, cssText }, artifacts };
  } finally {
    draft.close();
  }
}

async function scanJscssFiles(
  config: ResolvedVextFrontendConfig,
): Promise<string[]> {
  if (!existsSync(config.root)) return [];
  const files = await fg(config.styles.jscss.files, {
    cwd: config.root,
    absolute: true,
    onlyFiles: true,
    followSymbolicLinks: false,
    ignore: ["**/*.d.ts", "**/*.test.*", "**/*.spec.*"],
  });
  return files.sort((a, b) => a.localeCompare(b));
}

function renderExtractorEntry(generatedDir: string, files: string[]): string {
  const imports = files
    .map(
      (file, index) =>
        `import ${JSON.stringify(toImportSpecifier(generatedDir, file))}; // ${index}`,
    )
    .join("\n");
  return `/* This file is generated by vextjs. Do not edit it by hand. */
import { __vextGetStyleSheet } from "vextjs/style";
${imports}

export default __vextGetStyleSheet();
`;
}

function createJscssResolverPlugin(
  config: ResolvedVextFrontendConfig,
): esbuild.Plugin {
  return {
    name: "vext-jscss-resolver",
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        if (args.path === "vextjs/style") {
          return { path: resolveVextStyleModule() };
        }
        const aliasTarget = resolveAliasImport(config, args.path);
        if (aliasTarget) {
          return { path: resolveExistingModulePath(aliasTarget) };
        }
        return undefined;
      });
    },
  };
}

function resolveVextStyleModule(): string {
  const sourcePath = fileURLToPath(
    new URL("../style/index.ts", import.meta.url),
  );
  if (existsSync(sourcePath)) return sourcePath;
  return fileURLToPath(new URL("../style/index.js", import.meta.url));
}

function resolveAliasImport(
  config: ResolvedVextFrontendConfig,
  importPath: string,
): string | undefined {
  for (const [alias, target] of Object.entries(config.alias)) {
    if (importPath === alias) return target;
    if (importPath.startsWith(`${alias}/`)) {
      return path.join(target, importPath.slice(alias.length + 1));
    }
  }
  return undefined;
}

const JSCSS_RESOLVE_EXTENSIONS = [".ts", ".js", ".tsx", ".jsx", ".json"];

function resolveExistingModulePath(filePath: string): string {
  if (existsSync(filePath)) return filePath;
  for (const extension of JSCSS_RESOLVE_EXTENSIONS) {
    const candidate = `${filePath}${extension}`;
    if (existsSync(candidate)) return candidate;
  }
  for (const extension of JSCSS_RESOLVE_EXTENSIONS) {
    const candidate = path.join(filePath, `index${extension}`);
    if (existsSync(candidate)) return candidate;
  }
  return filePath;
}

function toImportSpecifier(fromDir: string, targetPath: string): string {
  const relative = path.relative(fromDir, targetPath).replace(/\\/g, "/");
  return relative.startsWith(".") ? relative : `./${relative}`;
}
