import type { AnalysisDomain } from "../tooling/diagnostics/contracts.js";

/** 知识、配方和能力共用静态 domain 词表；不通过标题关键词猜测归属。 */
const CATALOG_DOMAINS: Record<string, AnalysisDomain[]> = {
  C01: ["structure"],
  C02: ["structure"],
  C03: ["routes"],
  C04: ["routes", "docs"],
  C05: ["services"],
  C06: ["middlewares"],
  C07: ["plugins"],
  C08: ["models"],
  C09: ["frontend"],
  C10: ["frontend", "structure"],
  C11: ["i18n"],
  C12: ["configuration"],
  C13: ["docs"],
  C14: ["structure", "testing"],
  C15: ["testing"],
  C16: ["testing", "runtime"],
  C17: ["runtime"],
  C18: ["runtime"],
  C19: ["configuration", "routes"],
  C20: ["configuration", "middlewares"],
  C21: ["routes", "middlewares"],
  C22: ["routes", "configuration"],
  C23: ["structure"],
  C24: ["structure", "models"],
  C25: ["structure"],
  C26: ["structure"],
  C27: ["structure", "testing"],
  C28: ["runtime", "testing"],
  C29: ["configuration"],
  C30: ["configuration"],
  C31: ["docs"],
  C32: ["testing"],
  C33: ["dependencies"],
  C34: ["jobs"],
  R01: ["structure"],
  R02: ["runtime", "testing"],
  R03: ["structure"],
  R04: ["structure"],
  R05: ["structure"],
  R06: ["docs", "dependencies"],
  "WF-01": ["structure"],
  "WF-02": ["testing", "runtime"],
  "WF-03": ["testing"],
  "WF-04": ["testing", "runtime"],
  "RCP-01": ["routes"],
  "RCP-02": ["routes", "services"],
  "RCP-03": ["frontend", "routes"],
  "RCP-04": ["frontend", "routes"],
  "RCP-05": ["services"],
  "RCP-06": ["models"],
  "RCP-07": ["middlewares"],
  "RCP-08": ["plugins"],
  "RCP-09": ["i18n"],
  "RCP-10": ["testing"],
  "RCP-11": ["structure"],
  "RCP-12": ["structure"],
  "RCP-13": ["frontend"],
  "RCP-14": ["frontend"],
  "RCP-15": ["routes", "jobs"],
  "RCP-16": ["structure", "testing"],
  "RCP-17": ["jobs"],
  K01: ["dependencies", "routes", "i18n", "jobs"],
  K02: ["dependencies", "configuration", "routes"],
  K03: ["dependencies", "configuration", "middlewares"],
  K04: ["dependencies", "testing", "runtime"],
  K05: ["dependencies", "models"],
  K06: ["dependencies", "configuration"],
  K07: ["dependencies", "jobs"],
  K08: ["dependencies", "configuration", "jobs"],
  K09: ["dependencies", "configuration"],
  K10: ["dependencies", "frontend"],
  K11: ["dependencies", "testing"],
  K12: ["dependencies", "frontend"],
};

export function catalogDomains(id: string): AnalysisDomain[] {
  return CATALOG_DOMAINS[id] ?? [];
}
