// Auto-generated by vext typegen (experimental). DO NOT EDIT.

declare module "vextjs" {
  interface VextApp {
    mailer: { send(to: string, subject: string, body: string): Promise<void>; };
    readyState: { value: boolean; };
  }
}


