// Auto-generated by vext typegen (experimental). DO NOT EDIT.

import "vextjs";

declare module "vextjs" {
  interface VextServices {
    payment: {
      stripe: import("../../src/services/payment/stripe.js").default;
    };
    userProfile: import("../../src/services/user-profile.js").default;
  }
}
