// Auto-generated by vext typegen (experimental). DO NOT EDIT.

import "vextjs";

declare module "vextjs" {
  interface VextServices {
    payment: {
      stripe: import("../../services/payment/stripe.js").default;
    };
    userProfile: import("../../services/user-profile.js").default;
  }
}

