import { relative, sep } from "node:path";
import type { GeneratedFileResult } from "./write-generated-file.js";
import { writeGeneratedFile } from "./write-generated-file.js";
import { getTypegenGeneratedPaths } from "./generated-paths.js";

export async function generateTypegenShim(
  rootDir: string,
  generatedFiles: string[],
  options: { checkOnly?: boolean } = {},
): Promise<GeneratedFileResult> {
  const paths = getTypegenGeneratedPaths(rootDir);
  const references = generatedFiles
    .map((filePath) => toReferencePath(paths.shimDts, filePath))
    .sort((a, b) => a.localeCompare(b));

  const content = [
    "// Auto-generated by vext typegen. DO NOT EDIT.",
    ...references.map((ref) => `/// <reference path="${ref}" />`),
    "",
  ].join("\n");

  return writeGeneratedFile(paths.shimDts, content, options);
}

function toReferencePath(fromFile: string, toFile: string): string {
  let rel = relative(fromFile.replace(/[^/\\]+$/u, ""), toFile)
    .split(sep)
    .join("/");
  if (!rel.startsWith(".")) {
    rel = `./${rel}`;
  }
  return rel;
}
