import type { AppExtensionIndexEntry } from "../project-index/index.js";
import { mergeAppExtensions } from "./merge-app-extensions.js";
import type { GeneratedFileDraft } from "../../lib/project/generated-files.js";
import { getTypegenGeneratedPaths } from "./generated-paths.js";
import { renderTypePropertyKey } from "./property-key.js";

export interface AppExtensionsGenerationResult {
  file: GeneratedFileDraft;
  warnings: string[];
}

export function createAppExtensionsDts(
  rootDir: string,
  entries: AppExtensionIndexEntry[],
): AppExtensionsGenerationResult {
  const filePath = getTypegenGeneratedPaths(rootDir).appExtensionsDts;

  const merged = mergeAppExtensions(entries);

  const lines = [
    "// Auto-generated by vext typegen (experimental). DO NOT EDIT.",
    "",
    'import "vextjs";',
    "",
    'declare module "vextjs" {',
    "  interface VextApp {",
    ...merged.entries.map(
      (entry) =>
        `    ${renderTypePropertyKey(entry.propertyKey)}: ${entry.inferredTypeText};`,
    ),
    "  }",
    "}",
    "",
  ];

  return {
    file: { filePath, content: lines.join("\n"), producer: "typegen-types" },
    warnings: merged.warnings,
  };
}
