import type { ServiceIndexEntry } from "../project-index/index.js";
import {
  writeGeneratedFile,
  type GeneratedFileResult,
} from "./write-generated-file.js";
import { getTypegenGeneratedPaths } from "./generated-paths.js";

interface ServiceTreeNode {
  children: Map<string, ServiceTreeNode>;
  typeText?: string;
}

const IDENTIFIER_PROPERTY_NAME = /^[A-Za-z_$][\w$]*$/u;
const RESERVED_PROPERTY_NAMES = new Set([
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "var",
  "void",
  "while",
  "with",
  "as",
  "async",
  "await",
  "from",
  "get",
  "implements",
  "interface",
  "let",
  "of",
  "package",
  "private",
  "protected",
  "public",
  "set",
  "static",
  "yield",
]);

export async function generateServicesDts(
  rootDir: string,
  entries: ServiceIndexEntry[],
  options: { checkOnly?: boolean } = {},
): Promise<GeneratedFileResult> {
  const filePath = getTypegenGeneratedPaths(rootDir).servicesDts;

  const tree = createServiceTree(entries);
  const body = renderServiceTree(tree, 2);

  const content = [
    "// Auto-generated by vext typegen (experimental). DO NOT EDIT.",
    "",
    'import "vextjs";',
    "",
    'declare module "vextjs" {',
    "  interface VextServices {",
    body || "",
    "  }",
    "}",
    "",
  ]
    .filter((line, index, arr) => !(line === "" && arr[index - 1] === ""))
    .join("\n");

  return writeGeneratedFile(filePath, content, options);
}

function createServiceTree(entries: ServiceIndexEntry[]): ServiceTreeNode {
  const root: ServiceTreeNode = { children: new Map() };

  for (const entry of entries) {
    let current = root;
    for (const segment of entry.keySegments) {
      let next = current.children.get(segment);
      if (!next) {
        next = { children: new Map() };
        current.children.set(segment, next);
      }
      current = next;
    }
    current.typeText = `import("${entry.importPath}").default`;
  }

  return root;
}

function renderServiceTree(node: ServiceTreeNode, indentLevel: number): string {
  const indent = "  ".repeat(indentLevel);
  const lines: string[] = [];

  for (const [key, child] of [...node.children.entries()].sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    const propertyKey = renderServicePropertyKey(key);
    const hasChildren = child.children.size > 0;
    if (child.typeText && !hasChildren) {
      lines.push(`${indent}${propertyKey}: ${child.typeText};`);
      continue;
    }

    if (hasChildren && !child.typeText) {
      lines.push(`${indent}${propertyKey}: {`);
      lines.push(renderServiceTree(child, indentLevel + 1));
      lines.push(`${indent}};`);
      continue;
    }

    if (child.typeText && hasChildren) {
      lines.push(`${indent}${propertyKey}: ${child.typeText} & {`);
      lines.push(renderServiceTree(child, indentLevel + 1));
      lines.push(`${indent}};`);
    }
  }

  return lines.join("\n");
}

function renderServicePropertyKey(key: string): string {
  if (IDENTIFIER_PROPERTY_NAME.test(key) && !RESERVED_PROPERTY_NAMES.has(key)) {
    return key;
  }

  return JSON.stringify(key);
}
