import type { AppExtensionIndexEntry } from "../project-index/index.js";
import { mergeAppExtensions } from "./merge-app-extensions.js";
import {
  writeGeneratedFile,
  type GeneratedFileResult,
} from "./write-generated-file.js";
import { getTypegenGeneratedPaths } from "./generated-paths.js";

export interface AppExtensionsGenerationResult {
  file: GeneratedFileResult;
  warnings: string[];
}

export async function generateAppExtensionsDts(
  rootDir: string,
  entries: AppExtensionIndexEntry[],
  options: { checkOnly?: boolean } = {},
): Promise<AppExtensionsGenerationResult> {
  const filePath = getTypegenGeneratedPaths(rootDir).appExtensionsDts;

  const merged = mergeAppExtensions(entries);

  const lines = [
    "// Auto-generated by vext typegen (experimental). DO NOT EDIT.",
    "",
    'import "vextjs";',
    "",
    'declare module "vextjs" {',
    "  interface VextApp {",
    ...merged.entries.map(
      (entry) => `    ${entry.propertyKey}: ${entry.inferredTypeText};`,
    ),
    "  }",
    "}",
    "",
  ];

  return {
    file: await writeGeneratedFile(filePath, lines.join("\n"), options),
    warnings: merged.warnings,
  };
}
