import { relative, sep } from "node:path";
import type { GeneratedFileDraft } from "../../lib/project/generated-files.js";
import { getTypegenGeneratedPaths } from "./generated-paths.js";

export function createTypegenShim(
  rootDir: string,
  generatedFiles: string[],
): GeneratedFileDraft {
  const paths = getTypegenGeneratedPaths(rootDir);
  const references = generatedFiles
    .map((filePath) => toReferencePath(paths.shimDts, filePath))
    .sort((a, b) => a.localeCompare(b));

  const content = [
    "// Auto-generated by vext typegen. DO NOT EDIT.",
    ...references.map((ref) => `/// <reference path="${ref}" />`),
    "",
  ].join("\n");

  return { filePath: paths.shimDts, content, producer: "typegen-shim" };
}

function toReferencePath(fromFile: string, toFile: string): string {
  let rel = relative(fromFile.replace(/[^/\\]+$/u, ""), toFile)
    .split(sep)
    .join("/");
  if (!rel.startsWith(".")) {
    rel = `./${rel}`;
  }
  return rel;
}
